/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pilascolas;

import javax.swing.DefaultListModel;
import javax.swing.JList;
import pilascolas.PCFrame.Arreglo;


public class PCFrame extends javax.swing.JFrame {

    int toInt(Object o){
        return Integer.parseInt(o.toString());
    }
    
    class Entero {
        int val;
        public Entero(int val){
            this.val = val;
        }

        private Entero() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    }  
    
    class Nodo {
        int num;
    }
    
    class Arreglo {
        Nodo[] nodos;
        public Arreglo(){
            nodos = new Nodo[100];
        }
    }
    
    void inpila(Arreglo pila, Entero tope, int num){
        if(tope.val < 100) {
            Nodo nodo = new Nodo();
            nodo.num = num;
//            tope.val = tope.val + 1;
//            pila.nodos[tope.val] = nodo;
            pila.nodos[++tope.val] = nodo;
        }
    }
    
    Nodo canpila(Arreglo pila, Entero tope){
        if(tope.val > -1) {
            return pila.nodos[tope.val--];
//            Nodo n = pila.nodos[tope.val];
//            tope.val = tope.val - 1;
//            return n;
        } else {
            return null;
        }
    }
    
    void incola(Arreglo cola, Entero tope, int num) {
        inpila(cola, tope, num);
    }
    
    Nodo cancola(Arreglo cola, Entero tope, Entero base) {
        if(tope.val > -1) {
            Nodo primero = cola.nodos[0];
            for(int i = 1; i <= tope.val; ++i){
                cola.nodos[i - 1] = cola.nodos[i];
            }
            tope.val--;
            base.val++;
            return primero;
        } else {
            return null;
        }
    }
    
    void escribirArreglo(Arreglo pila, Entero tope, JList lista) {
        DefaultListModel model = (DefaultListModel) lista.getModel();
        model.clear();
        for(int i = tope.val; i > -1 ; --i){
            model.addElement(pila.nodos[i].num);
        }
    }
    
    void invertircola(Arreglo cola ,Entero tope,Entero base,JList lista){
        Entero tope1=new Entero();
        tope1.val=0;
        while (base.val!=tope.val) {            
         int a = cancola(cola,tope,base).num;
         inpila(pila,tope1,a);
        }
        while (tope1.val!=0) {            
            int b =canpila(pila,tope1).num;
            incola(cola,tope,b);
        }
    
    
    }
    
    
    Arreglo pila = new Arreglo();
    Entero tope = new Entero(-1);
    Entero base= new Entero();
    Arreglo cola = new Arreglo();
    Entero topeCola = new Entero(-1);
    
    /**
     * Creates new form PCFrame
     */
    public PCFrame() {
        initComponents();
        DefaultListModel model = new DefaultListModel();
        lista.setModel(model);
        model = new DefaultListModel();
        listaCola.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        numeroTextField = new javax.swing.JTextField();
        agregarPila = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList<>();
        eliminarPila = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ultimoLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        numeroCola = new javax.swing.JTextField();
        agregarCola = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaCola = new javax.swing.JList<>();
        eliminarCola = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        ultimoCola = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Número:");

        agregarPila.setText("Agregar Pila");
        agregarPila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarPilaActionPerformed(evt);
            }
        });

        lista.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lista);

        eliminarPila.setText("Retirar pila");
        eliminarPila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarPilaActionPerformed(evt);
            }
        });

        jLabel2.setText("Ultimo número:");

        jLabel3.setText("Número:");

        agregarCola.setText("Agregar Cola");
        agregarCola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarColaActionPerformed(evt);
            }
        });

        listaCola.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listaCola);

        eliminarCola.setText("Retirar cola");
        eliminarCola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarColaActionPerformed(evt);
            }
        });

        jLabel4.setText("Ultimo número:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(agregarPila, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numeroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(eliminarPila, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ultimoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(agregarCola, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numeroCola, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(eliminarCola, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ultimoCola, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(numeroCola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(agregarCola)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eliminarCola)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(ultimoCola)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(numeroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(agregarPila)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eliminarPila)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(ultimoLabel))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarPilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarPilaActionPerformed
        int num = toInt(numeroTextField.getText());
        inpila(pila, tope, num);
        escribirArreglo(pila, tope, lista);
    }//GEN-LAST:event_agregarPilaActionPerformed

    private void eliminarPilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarPilaActionPerformed
        Nodo n = canpila(pila, tope);
        if (n != null) {
            ultimoLabel.setText(n.num + "");
        }
        escribirArreglo(pila, tope, lista);
    }//GEN-LAST:event_eliminarPilaActionPerformed

    private void agregarColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarColaActionPerformed
        int num = toInt(numeroCola.getText());
        incola(cola, topeCola, num);
        escribirArreglo(cola, topeCola, listaCola);
    }//GEN-LAST:event_agregarColaActionPerformed

    private void eliminarColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarColaActionPerformed
        Nodo n = cancola(cola, topeCola);
        if(n != null){
            ultimoCola.setText(n.num + "");
        }
        escribirArreglo(cola, topeCola, listaCola);
    }//GEN-LAST:event_eliminarColaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PCFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PCFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PCFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PCFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PCFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarCola;
    private javax.swing.JButton agregarPila;
    private javax.swing.JButton eliminarCola;
    private javax.swing.JButton eliminarPila;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lista;
    private javax.swing.JList<String> listaCola;
    private javax.swing.JTextField numeroCola;
    private javax.swing.JTextField numeroTextField;
    private javax.swing.JLabel ultimoCola;
    private javax.swing.JLabel ultimoLabel;
    // End of variables declaration//GEN-END:variables
}
